### PR TITLE
Add support for MessagePack serialization

### PR DESCRIPTION
**Pull request by jrogers**
Adds msgpack serialization support using msgpack-jackson in v0.7.0.

### CODE REVIEW

**Comment by jrogers** [comment]
I was thinking it might be useful to make msgpack support an optional dependency. I wanted to get your thoughts on that, as well as where I create ObjectMapper's for both JSON and MessagePack in the enum and not on demand. I can easily do both by checking for msgpack support at runtime, as well as creating a factory abstration for creating serializers on demand, vs. in the Serialization enum constructor like it does right now.

**Comment by Matthias247** [comment]
Sorry that I didn't react earlier, but I'm currently quite busy. I will try to take a look at it ASAP. Messagepack support does definitly sound cool and I'm happy that someone started working on it :)

**Comment by jrogers** [comment]
Any comments?

**Comment by Matthias247** [comment]
Hello Jeff,
sorry for the delay. Just looked through it. It looks straightforward and much easier than I thought it might be - didn't know that Messagepack for Java provides a Json compatible interface.

One thing that I'm not sure of is that we now have 2 ObjectMappers - on in the client and one further down in the [De]Serializer. But I guess this isn't a problem - because the upper one is only used for object mapping (Java types to Json Types) and the lower one for the serialization?
If that's the case we should also remove the ObjectMapper parameter from `WampClientChannelFactory`.

Another thing that I have seen is that you also have inserted logging statements for the binary messages like:

    logger.debug("Deserialized Wamp Message: {}", textFrame.content().toString());

Don't think that makes sense because the content is not only UTF8 but messagepack encoded which would make the string output unreadable. Maybe it could be logged before serialization / after serialization.

Regarding a dependency to MessagePack or adding runtime checking: I personally don't mind the dependency because I think most users would be happy if their server could serve as much clients or connect to as much servers as possible. And compared to Jackson and Netty the MessagePack library is quite tiny so the overhead is neglible.

**Comment by jrogers** [comment]
Thanks I'll put an updated patch together to clean up the logging and update the dependency versions as msgpack-java has moved quite a bit.

For your first question about the ObjectMapper, yes you're right, the first one is only used for mapping and the second one is used for the actual serialization (the MessagePackFactory passed to the second ObjectMapper only affects the serialization/deserialization, not the actual type mapping) so I think it's ok. 
I think I already removed the parameter in my change no?

**Comment by jrogers** [comment]
Updated the readme as well.

**Comment by Matthias247** [comment]
Looks good to me now! I have merged it. Of course you already had the parameter removed, I overlooked that since I viewed the original version in my editor in parallel to the diff.

Thanks for the effort and for the contribution!

**Pull request merged**
